# fly.toml app configuration file generated for collie-defense-scores on 2023-10-14T16:32:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "collie-defense-scores"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
